Class {
	#name : #FylgjaTranslateModifyExistingOrCreateStub,
	#superclass : #FylgjaOperation,
	#category : #'Fylgja-Test-VWPharo'
}

{ #category : #'as yet unclassified' }
FylgjaTranslateModifyExistingOrCreateStub >> applyTo: aRelatedProvenanceEntity croppingRelationsWith: aBlock destinationWriter: aDestinationWriter lookUp: aFylgjaLookUpContext using: aFylgjaDerivativeModel [
	self shouldBeImplemented.
]
